name: Entrega Continua

on:
  workflow_call:

jobs:

  AWS:
    runs-on: ubuntu-latest
    steps:
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: programa
        path: ./

    # - uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_AWS }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST_AWS }}
        REMOTE_USER: ${{ secrets.REMOTE_USER_AWS }}
        TARGET: /home/${{ secrets.REMOTE_USER_AWS }}
        EXCLUDE: "postgres-data"
        SCRIPT_AFTER: |
          export DB_HOST=${{ secrets.DB_HOST_AWS }}
          export DB_USER=${{ secrets.DB_USER_AWS }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD_AWS }}
          export DB_DBNAME=${{ secrets.DB_NAME_AWS }}
          export DB_PORT=${{ secrets.DB_PORT_AWS }}
          export PORT=8000
          export SSL_MODE=require
  
          # Verificar se o arquivo main está no diretório atual
          ls -l
          
          chmod +x main
          nohup ./main &
          
      