name: Entrega Continua

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
    # Artifact name
        name: programa

    - uses: actions/checkout@v3