name: Entrega Continua

on:
  workflow_call:

jobs:

  AWS:
    runs-on: ubuntu-latest
    steps:
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: programa
        path: ./


    - uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_AWS }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST_AWS }}
        REMOTE_USER: ${{ secrets.REMOTE_USER_AWS }}
        TARGET: /home/${{ secrets.REMOTE_USER_AWS }}
        EXCLUDE: "postgres-data"

        SCRIPT_AFTER: |
          # Mudar para o diretório correto
          cd /home/${{ secrets.REMOTE_USER_AWS }}

          # Garantir que o arquivo main tenha permissões de execução
          chmod +x main

           # Criar um script temporário com as variáveis de ambiente

          echo "#!/bin/bash" > run_main.sh
          echo "export DB_HOST=${{ secrets.DB_HOST_AWS }}" >> run_main.sh
          echo "export DB_USER=${{ secrets.DB_USER_AWS }}" >> run_main.sh
          echo "export DB_PASSWORD=${{ secrets.DB_PASSWORD_AWS }}" >> run_main.sh
          echo "export DB_NAME=${{ secrets.DB_NAME_AWS }}" >> run_main.sh
          echo "export DB_PORT=${{ secrets.DB_PORT_AWS }}" >> run_main.sh
          echo "export DB_SSLMODE=require" >> run_main.sh
          echo "./main > nohup.out 2> nohup.err < /dev/null &" >> run_main.sh

          # Dar permissão para o script e executá-lo
          chmod +x run_main.sh
          nohup ./run_main.sh > nohup.out 2> nohup.err < /dev/null & 
          

                