name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: root
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Build Database
        run: docker compose build

      - name: Start Database
        run: docker compose up -d postgres

      - name: Check PostgreSQL Logs
        run: docker compose logs postgres

      - name: Check PostgreSQL Connection
        run: |
          echo "Verificando conexão com PostgreSQL..."
          for i in {1..20}; do
            if docker exec $(docker ps -qf "name=postgres") pg_isready -h localhost -U root -d root -p 5432; then
              echo "Conexão bem-sucedida!"
              exit 0
            fi
            echo "Tentativa $i: PostgreSQL não está pronto. Aguardando..."
            sleep 5
          done
          echo "Erro: PostgreSQL não está respondendo após 20 tentativas."
          exit 1

      - name: Run Tests
        run: go test -v main_test.go

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          args: controllers/ database/ models/ routes/

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: go build -o main -v main.go

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: programa
          path: main

  deploy-ec2:
    needs: build
    uses: ./.github/workflows/Entrega-Continua.yml
    secrets: inherit
